- hosts: base-image
  become: yes
  
  vars:
    - pgversion: 12

  tasks:
    - name: Add  PostgreSQL repo key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repository
      apt_repository: 
        repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
        state: present
        update_cache: true

    - name: Ensure postgresql database-cluster manager package
      package:
        name: postgresql-common
        update_cache: yes

    - name: Disable initializing of a default postgresql cluster
      replace:
        path: /etc/postgresql-common/createcluster.conf
        replace: create_main_cluster = false
        regexp: ^#?create_main_cluster.*$

    - name: Install postgresql packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - postgresql-{{ pgversion }}
        - postgresql-client-{{ pgversion }}
        - postgresql-contrib-{{ pgversion }}
